name: Generate Datas

on:
  schedule: # executar a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Animação de cobra
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Allan177
          svg_out_path: dist/github-contribution-grid-snake.svg
